// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupVt-yol7PEKIMPXYNm7WIVEaIu8r9Po',
    appId: '1:505382490993:web:55afd6de32e47341105cd0',
    messagingSenderId: '505382490993',
    projectId: 'apptareas-4af8d',
    authDomain: 'apptareas-4af8d.firebaseapp.com',
    storageBucket: 'apptareas-4af8d.firebasestorage.app',
    measurementId: 'G-2R6PXWVEXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm4MNluLggTxPShEExO6usTu-xHWYz-3o',
    appId: '1:505382490993:android:fa469241c005bb10105cd0',
    messagingSenderId: '505382490993',
    projectId: 'apptareas-4af8d',
    storageBucket: 'apptareas-4af8d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBupVt-yol7PEKIMPXYNm7WIVEaIu8r9Po',
    appId: '1:505382490993:web:55afd6de32e47341105cd0',
    messagingSenderId: '505382490993',
    projectId: 'apptareas-4af8d',
    authDomain: 'apptareas-4af8d.firebaseapp.com',
    storageBucket: 'apptareas-4af8d.firebasestorage.app',
    measurementId: 'G-2R6PXWVEXF',
  );
}
